include:
 - sketch:
    - extras/arduino-examples/examples/01.Basics/Blink/Blink.ino
    - extras/arduino-examples/examples/03.Analog/AnalogInOutSerial/AnalogInOutSerial.ino
    - extras/arduino-examples/examples/02.Digital/toneMultiple/toneMultiple.ino
