package-name: arduino-core-psoc6
include:
  - cores
  - examples
  - extras/mtb-libs
  - libraries
  - tools
  - variants
  - boards.txt
  - platform.txt
  - LICENSE.md
  - README.md
  - post_install.sh
index-name: package_psoc6_index
server: 
  type: github
  owner: Infineon
  repo: arduino-core-psoc6
 
 