name: Build check

# on which event should we start push, pull request or schedule dispatches
on:
  - push
  - pull_request

jobs:

  set-ci-matrix:
    runs-on: ubuntu-latest
    outputs:
      ci-matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set build matrix
        id: set-matrix
        run: |
          ci_matrix=$(cat ci-build-matrix.json)
          echo "::set-output name=matrix::$ci_matrix"

  build:

    # we run this on self hosted runner, use labels to be more specific
    # add specific names if there are some, otherwise self-hosted, X64, Linux are the default ones
    runs-on:
      - ubuntu-latest

    strategy:
      matrix: 
        config: ${{ fromJSON(needs.set-ci-matrix.outputs.ci-matrix) }}

      matrix:
        # List of all examples in the lib to compile
        example: [
            examples/testSketch/testSketch.ino
        ]

        # board packages we want to run
        # attention the matrix spans over the fqbn not platform so that we can choose different boards
        fqbn: [
          "infineon:psoc:cy8ckit_062s2_ai"
        ]

        # include additional information for each fqbn, in this case the platform name to install
        include:
        - fqbn:     "infineon:psoc:cy8ckit_062s2_ai"
          platform: "infineon:psoc"

    # These are the steps which should run for each combination of fqbn and example code
    steps:

      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0
        
      - name: Install arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 1.1.0
          sudo mv bin/arduino-cli /usr/local/bin/arduino-cli
          arduino-cli version

      - name: Pack Arduino core
        run: |
          bash ./tools/dev-setup.sh
          python ./tools/arduino-packager.py --no-version-check --no-previous-releases
  
      - name: Install Arduino core
        run: |
          python ./tools/pckg-install-local.py --pckg-dir build

      - name: Compile Sketch
        run: |
          arduino-cli compile --clean --verbose --fqbn ${{ matrix.fqbn }} ${{ matrix.example }}