name: Compile examples

# comment to trigger change. 123
on:
  push:
    
jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@split-package-core
    with:
      ci-matrix-file-json: ci-build-matrix.json
      setup-script: bash ./tools/dev-setup.sh
    secrets: inherit