name: Compile examples

on:
  pull_request:
#  push:
    
jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@latest
    with:
      core-setup-script: bash ./tools/dev-setup.sh
      ci-setup-script: git submodule update --init extras/arduino-examples
    secrets: inherit